name: Build documentation

on:
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: build docs
      run: TRAVIS_BRANCH=master ./tools/travis_update_docs.sh
