name: Tests

on:
  push:
    branches:
      - master
      - ci-gh-actions
  pull_request:
    branches: [ master ]

jobs:
  python:
    name: Python implementation
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 11
            python: 3.6
          - postgres: 12
            python: 3.7
          - postgres: 12
            python: 3.8

    env:
      PSYCOPG3_IMPL: python
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password
      PSYCOPG3_TEST_DSN: "dbname=postgres"

    services:
      postgresql:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: install tox
      run: pip install tox
    - name: run tests
      run: tox -c psycopg3 -e ${{ matrix.python }}

  c:
    name: C implementation
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - postgres: 10
            python: 3.6
          - postgres: 11
            python: 3.7
          - postgres: 12
            python: 3.8

    env:
      PSYCOPG3_IMPL: c
      PGHOST: 127.0.0.1
      PGUSER: postgres
      PGPASSWORD: password
      PSYCOPG3_TEST_DSN: "dbname=postgres"
      # skip tests failing on importing psycopg3_c.pq on subprocess
      # they only fail on Travis, work ok locally under tox too.
      PYTEST_ADDOPTS: "-m 'not subprocess'"

    services:
      postgresql:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: install tox
      run: pip install tox
    - name: run tests
      run: tox -c psycopg3_c -e ${{ matrix.python }}
