name: Tests

on:
  push:
  pull_request:

jobs:
  linux:
    name: Test on Linux
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - {impl: python, python: 3.6, postgres: 10}
          - {impl: python, python: 3.7, postgres: 11}
          - {impl: python, python: 3.8, postgres: 12}
          - {impl: python, python: 3.9, postgres: 13}
          - {impl: c, python: 3.6, postgres: 13}
          - {impl: c, python: 3.7, postgres: 12}
          - {impl: c, python: 3.8, postgres: 11}
          - {impl: c, python: 3.9, postgres: 10}

    env:
      PSYCOPG_IMPL: ${{ matrix.impl }}
      PSYCOPG_TEST_DSN: "host=127.0.0.1 user=postgres"
      PGPASSWORD: password

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tests (Python implementation)
        run: tox -c psycopg -e ${{ matrix.python }} -- --color yes
        if: ${{ matrix.impl == 'python' }}

      - name: Run tests (C implementation)
        run: tox -c psycopg_c -e ${{ matrix.python }} -- --color yes
        if: ${{ matrix.impl == 'c' }}
        env:
          # skip tests failing on importing psycopg_c.pq on subprocess
          # they only fail on Travis, work ok locally under tox too.
          PYTEST_ADDOPTS: "-m 'not subprocess'"

    services:
      postgresql:
        image: postgres:${{ matrix.postgres }}
        env:
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


  macos:
    name: Test on MacOS
    runs-on: macos-10.15

    strategy:
      fail-fast: false
      matrix:
        include:
          - {impl: c, python: 3.6}
          - {impl: c, python: 3.7}
          - {impl: c, python: 3.8}
          - {impl: c, python: 3.9}
          - {impl: python, python: 3.9}

    env:
      PSYCOPG_IMPL: ${{ matrix.impl }}
      PSYCOPG_TEST_DSN: "host=127.0.0.1 user=runner dbname=postgres"
      # MacOS on GitHub Actions seems particularly slow.
      # Don't run timing-based tests as they regularly fail.
      # pproxy-based tests fail too, with the proxy not coming up in 2s.
      PYTEST_ADDOPTS: "-m 'not timing and not proxy'"

    steps:
      - uses: actions/checkout@v2

      - name: Install PostgreSQL on the runner
        run: brew install postgresql@13

      - name: Start PostgreSQL service for test
        run: brew services start postgresql

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tests (Python implementation)
        run: tox -c psycopg -e ${{ matrix.python }} -- --color yes
        if: ${{ matrix.impl == 'python' }}

      - name: Run tests (C implementation)
        run: tox -c psycopg_c -e ${{ matrix.python }} -- --color yes
        if: ${{ matrix.impl == 'c' }}


  windows:
    name: Test on Windows
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        include:
          # - {impl: c, python: 3.6}
          # - {impl: c, python: 3.7}
          - {impl: c, python: 3.8}
          # - {impl: c, python: 3.9}
          - {impl: python, python: 3.9}

    env:
      PSYCOPG_IMPL: ${{ matrix.impl }}
      PSYCOPG_TEST_DSN: "host=127.0.0.1 dbname=postgres"
      # On windows pproxy doesn't seem very happy.
      PYTEST_ADDOPTS: "-m 'not proxy'"

    steps:
      - uses: actions/checkout@v2

      - name: Start PostgreSQL service for test
        run: |
          $postgreSqlSvc = Get-Service "postgresql*"
          Set-Service $postgreSqlSvc.Name -StartupType manual
          $postgreSqlSvc.Start()

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Run tests (Python implementation)
        run: tox -c psycopg -e ${{ matrix.python }} -- --color yes
        if: ${{ matrix.impl == 'python' }}

      - name: Run tests (C implementation)
        run: tox -c psycopg_c -e ${{ matrix.python }} -- --color yes
        if: ${{ matrix.impl == 'c' }}
